name: green_capture
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0-191.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1

  fluttertoast: ^8.2.6
  flutter_speed_dial: ^7.0.0

  connectivity_plus: ^6.0.3
  package_info_plus: ^8.0.0
  open_filex: ^4.4.0
  uuid: ^4.4.0
  dio: ^5.4.3+1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  syncfusion_flutter_datepicker: ^26.1.41

  hive: ^2.2.3
  path_provider: ^2.1.3

  http_parser: ^4.0.2

  intl: ^0.19.0
  flutter_launcher_icons: ^0.13.1
  camera: ^0.11.0+2
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

flutter_icons:
  android: "ic_launcher"
  image_path: "assets/icons/ic_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/ic_launcher_foreground.png"
